apiVersion: v1
baseDomain: okd.local
metadata:
  name: lab

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2dpYXR1bGUxYjVqOWl2ZzRmdzdneGp2OGR5ZGhncmhqZGs6TTMxUkJPVjg5R0lDRktSWTJFOTRTVEY0UkU3UjdNUVU4MzNZQjM0UFBKUllFOEdWQTRNQVc3UlJJN0pIRkQ5OA==","email":"giatule@gmail.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2dpYXR1bGUxYjVqOWl2ZzRmdzdneGp2OGR5ZGhncmhqZGs6TTMxUkJPVjg5R0lDRktSWTJFOTRTVEY0UkU3UjdNUVU4MzNZQjM0UFBKUllFOEdWQTRNQVc3UlJJN0pIRkQ5OA==","email":"giatule@gmail.com"},"registry.connect.redhat.com":{"auth":"NjIyNTIxMXx1aGMtMWI1ajlpdmc0Znc3Z3hKVjhkWURIZ3JISkRrOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKaU56QTFPRGMzTWpnME1HUTBaalEzWVRJd1pHRTVNbVk0TW1Vd05XSmxaaUo5LkRSd0l5U1Y4d3pZcUMyNXBGUUJwU0ZTQXg0Sl9acmRnanh2bUJqN2R3V2hmUHFpS21hQXF1S0ZkMjZ3UUVXOTlLemh2aTR4V0dIa280R1dOdGxRMDFCbGNQd2ZhS0pFazNjbDJsRW83clljNl9EX0ZZeDF6V080YnJuMGNyMTRmVGZoOTFvQzBfZGRid2o4dmQ4V0gyS0ZIbmszS2dXN01OeDgweU54M2EyN1JKOTR2dVpmRk1BUkkySWFYRHFQWTRpNndsR21WbXZkdUJ2SGpWeWttRElQaE5BZ0JHZ19qLWhKbmNra0hmM0dQN0N1MTl4VGoxQnlOazlXd3BnRWZzYlZIY0ozdkU2YzNWZW8zUEpFYnRXeXJKdUN2UTNTQVIwdmNVMVhHYUpDakszQ19NNlcxSGZ3bjF5MVJIS0pwWnFpMDRMMEt2RWV3Sk90ek9VWkJSTHFwTUZiQjZhTk9PY0dfSVpvd0xZV1VseXl4cFh2blRUUnNKQm02eDFsdWdDenNoV01lRWNzRFM3V0RQeEdQazljRnZXeXZyN2xDRWNnXzlDeDVaRUt3WTJBSmFmdjJDZ3k4RlhUaUNNRWdfVWtJTTlFeFJ6VWFPSkdZZjZ3Wll3MFB3MjV4SUlLRVNJeVJma1JCX2ZNMUZXMXlWUnVDOXZ2b25ESzZySTQzNWZXSXI3RTdPMkxIRkJZaTlNTUVYVmQyMFI5cUJ0OXhzYjI3Q25tWGVDZnZubWNnRWpXVzRlVkFLaTJuaG9YTFFHOXZqUW9PbFE5Uy00THh2b3N6eVJCNGZqUmdYdm1tYVdlV0g0enB6NWFoOTllM1dpYWVXQ2o0OEsyZVNoR1lmcDVwU0tQOFJidWl5TmV0MVFLam9RVldoWFRvZ2xNbWJia0dvTHlwVVln","email":"giatule@gmail.com"},"registry.redhat.io":{"auth":"NjIyNTIxMXx1aGMtMWI1ajlpdmc0Znc3Z3hKVjhkWURIZ3JISkRrOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKaU56QTFPRGMzTWpnME1HUTBaalEzWVRJd1pHRTVNbVk0TW1Vd05XSmxaaUo5LkRSd0l5U1Y4d3pZcUMyNXBGUUJwU0ZTQXg0Sl9acmRnanh2bUJqN2R3V2hmUHFpS21hQXF1S0ZkMjZ3UUVXOTlLemh2aTR4V0dIa280R1dOdGxRMDFCbGNQd2ZhS0pFazNjbDJsRW83clljNl9EX0ZZeDF6V080YnJuMGNyMTRmVGZoOTFvQzBfZGRid2o4dmQ4V0gyS0ZIbmszS2dXN01OeDgweU54M2EyN1JKOTR2dVpmRk1BUkkySWFYRHFQWTRpNndsR21WbXZkdUJ2SGpWeWttRElQaE5BZ0JHZ19qLWhKbmNra0hmM0dQN0N1MTl4VGoxQnlOazlXd3BnRWZzYlZIY0ozdkU2YzNWZW8zUEpFYnRXeXJKdUN2UTNTQVIwdmNVMVhHYUpDakszQ19NNlcxSGZ3bjF5MVJIS0pwWnFpMDRMMEt2RWV3Sk90ek9VWkJSTHFwTUZiQjZhTk9PY0dfSVpvd0xZV1VseXl4cFh2blRUUnNKQm02eDFsdWdDenNoV01lRWNzRFM3V0RQeEdQazljRnZXeXZyN2xDRWNnXzlDeDVaRUt3WTJBSmFmdjJDZ3k4RlhUaUNNRWdfVWtJTTlFeFJ6VWFPSkdZZjZ3Wll3MFB3MjV4SUlLRVNJeVJma1JCX2ZNMUZXMXlWUnVDOXZ2b25ESzZySTQzNWZXSXI3RTdPMkxIRkJZaTlNTUVYVmQyMFI5cUJ0OXhzYjI3Q25tWGVDZnZubWNnRWpXVzRlVkFLaTJuaG9YTFFHOXZqUW9PbFE5Uy00THh2b3N6eVJCNGZqUmdYdm1tYVdlV0g0enB6NWFoOTllM1dpYWVXQ2o0OEsyZVNoR1lmcDVwU0tQOFJidWl5TmV0MVFLam9RVldoWFRvZ2xNbWJia0dvTHlwVVln","email":"giatule@gmail.com"}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8lPwK7xfKrHQ6ZRq+XL28zIE2jv3Ai8DfHwj1py5xb5Ki3b/Gno4MY2BG4a5GZB0ZHHsbuOjMwP2djwWXIlu4EsKf+aKCXRYXD5VEIqfzjLUKBsYytnnkptAJNvD1jgDDRjooOhMcngc9zhzMeEJWgWGMwgiiPnzYogewQOfyPUXledFIY/VWefXHNS3t5IgKDTahFACtGxGdb1ChrQH9FV63Y7/ppELGoh2HWJ0PE56E0QQM98KYDMI04IijsJJM98HDFaIFGgDzf1ElGqBrr5rVsXnHl5l2X2DhGOGU69KSNyrBncbf5SlT54yTIalGGCDPT6oQL4u0X7ge0fJx core@services'
